# Generated by Django 5.2.7 on 2025-10-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_messagemodel_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='message',
            field=models.TextField(max_length=3000),
        ),
    ]
