# Generated by Django 5.2.7 on 2025-11-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sociallinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialLinks',
            new_name='SocialLink',
        ),
    ]
