# Generated by Django 5.2.7 on 2025-11-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_sociallink_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
