# Generated by Django 5.2.7 on 2025-11-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_sociallink_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.ImageField(upload_to='media/social_links'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='order',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(),
        ),
    ]
