# Generated by Django 5.2.7 on 2025-11-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_sociallink_icon_alter_sociallink_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='order',
            field=models.PositiveSmallIntegerField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'forth')]),
        ),
    ]
