# Generated by Django 5.2.7 on 2025-11-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_sociallink_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=150)),
                ('paragraph1', models.TextField()),
                ('paragraph2', models.TextField()),
            ],
        ),
    ]
