# Generated by Django 5.2.7 on 2025-11-02 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_contacttext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacttext',
            options={'verbose_name': 'ContactText'},
        ),
    ]
