# Generated by Django 5.2.7 on 2025-11-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_contacttext_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=80)),
                ('emoji', models.CharField(max_length=1)),
            ],
        ),
    ]
