# Generated by Django 5.2.7 on 2025-11-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_matrixprotocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixprotocol',
            name='emoji',
            field=models.CharField(max_length=2),
        ),
    ]
