# Generated by Django 5.2.7 on 2025-11-02 18:03

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_matrixprotocol_emoji'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='2025', max_length=10)),
                ('company_name', models.CharField(max_length=100)),
                ('rights_text', models.CharField(max_length=200)),
                ('design_by', models.CharField(max_length=100)),
                ('enhanced_by', models.CharField(max_length=100)),
                ('framework', models.CharField(default='Django-Python', max_length=100)),
                ('github_url', models.ForeignKey(blank=True, default=main.models.FooterInfo.get_default_github, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sociallink')),
            ],
            options={
                'verbose_name': 'FooterInfo',
                'verbose_name_plural': 'FooterInfo',
            },
        ),
    ]
