# Generated by Django 5.2.7 on 2025-11-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_footerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerinfo',
            name='framework_url',
            field=models.URLField(default='https://www.djangoproject.com'),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='framework',
            field=models.CharField(default='Django-Framework', max_length=100),
        ),
    ]
