# Generated by Django 5.2.7 on 2025-11-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_footerinfo_framework_url_alter_footerinfo_framework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerinfo',
            name='year',
            field=models.CharField(default='2025', max_length=4),
        ),
    ]
