# Generated by Django 5.2.7 on 2025-11-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_footerinfo_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerinfo',
            name='designer_url',
            field=models.URLField(default='https://templatemo.com'),
            preserve_default=False,
        ),
    ]
