# Generated by Django 5.2.7 on 2025-11-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_footerinfo_designer_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'TimeLineEvent',
                'verbose_name_plural': 'TimeLineEvent',
                'ordering': ['year'],
            },
        ),
    ]
