# Generated by Django 5.2.7 on 2025-11-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_timelineevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantumCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('emoji', models.CharField(max_length=2)),
                ('image', models.ImageField(upload_to='media/quantum_capabilities_img')),
            ],
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.ImageField(upload_to='media/social_links_img'),
        ),
    ]
