# Generated by Django 5.2.7 on 2025-11-03 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_quantumcapability_alter_sociallink_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('emoji', models.CharField(max_length=2)),
                ('image', models.ImageField(upload_to='media/quantum_capabilities_img')),
                ('section', models.ForeignKey(default=2, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.section')),
            ],
            options={
                'verbose_name': 'QuantumCapability',
                'verbose_name_plural': 'QuantumCapabilities',
            },
        ),
        migrations.CreateModel(
            name='Section3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=80)),
                ('emoji', models.CharField(max_length=2)),
                ('section', models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.section')),
            ],
        ),
        migrations.CreateModel(
            name='Section4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('section', models.ForeignKey(default=4, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.section')),
            ],
            options={
                'verbose_name': 'TimeLineEvent',
                'verbose_name_plural': 'TimeLineEvent',
                'ordering': ['year'],
            },
        ),
        migrations.DeleteModel(
            name='MatrixProtocol',
        ),
        migrations.DeleteModel(
            name='QuantumCapability',
        ),
        migrations.DeleteModel(
            name='TimeLineEvent',
        ),
    ]
