# Generated by Django 5.2.7 on 2025-11-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_section_section2_section3_section4_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section2',
            options={'verbose_name': 'Section2', 'verbose_name_plural': 'Section2'},
        ),
        migrations.AlterModelOptions(
            name='section3',
            options={'verbose_name': 'Section3', 'verbose_name_plural': 'Section3'},
        ),
        migrations.AlterModelOptions(
            name='section4',
            options={'ordering': ['year'], 'verbose_name': 'Section4', 'verbose_name_plural': 'Section4'},
        ),
    ]
