# Generated by Django 5.2.7 on 2025-11-03 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_section2_options_alter_section3_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='section2',
            options={'verbose_name': 'Section3', 'verbose_name_plural': 'Section3'},
        ),
        migrations.AlterModelOptions(
            name='section3',
            options={'ordering': ['year'], 'verbose_name': 'Section4', 'verbose_name_plural': 'Section4'},
        ),
        migrations.AlterModelOptions(
            name='section4',
            options={'verbose_name': 'Section2', 'verbose_name_plural': 'Section2'},
        ),
        migrations.RemoveField(
            model_name='section2',
            name='image',
        ),
        migrations.RemoveField(
            model_name='section3',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='section4',
            name='year',
        ),
        migrations.AddField(
            model_name='section3',
            name='year',
            field=models.CharField(default='11', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section4',
            name='emoji',
            field=models.CharField(default='1', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section4',
            name='image',
            field=models.ImageField(default='puh.png', upload_to='media/quantum_capabilities_img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section2',
            name='description',
            field=models.TextField(max_length=80),
        ),
        migrations.AlterField(
            model_name='section2',
            name='section',
            field=models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.section'),
        ),
        migrations.AlterField(
            model_name='section3',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='section3',
            name='section',
            field=models.ForeignKey(default=4, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.section'),
        ),
        migrations.AlterField(
            model_name='section3',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='section4',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='section4',
            name='section',
            field=models.ForeignKey(default=2, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.section'),
        ),
        migrations.AlterField(
            model_name='section4',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
