# Generated by Django 5.2.7 on 2025-11-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_section2_options_alter_section3_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveSmallIntegerField(choices=[('1', 'first'), ('2', 'second'), ('3', 'third'), ('4', 'forth')], default=1),
            preserve_default=False,
        ),
    ]
