# Generated by Django 5.2.7 on 2025-11-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_section_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveSmallIntegerField(choices=[('1', 'first'), ('2', 'second'), ('3', 'third'), ('4', 'forth')], unique=True),
        ),
    ]
