# Generated by Django 5.2.7 on 2025-11-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_section_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(max_length=60),
        ),
    ]
