# Generated by Django 5.2.7 on 2025-11-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_section_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveSmallIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
