# Generated by Django 5.2.7 on 2025-11-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_section_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
    ]
