# Generated by Django 5.2.7 on 2025-11-03 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_section_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='media/logo')),
                ('title', models.CharField(max_length=75)),
                ('sub_title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='section2',
            options={'verbose_name': 'Section3', 'verbose_name_plural': 'Section3'},
        ),
        migrations.AlterModelOptions(
            name='section3',
            options={'ordering': ['year'], 'verbose_name': 'Section4', 'verbose_name_plural': 'Section4'},
        ),
        migrations.RemoveField(
            model_name='section2',
            name='image',
        ),
        migrations.RemoveField(
            model_name='section3',
            name='emoji',
        ),
        migrations.AddField(
            model_name='section3',
            name='year',
            field=models.CharField(default='22', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')]),
        ),
        migrations.AlterField(
            model_name='section2',
            name='description',
            field=models.TextField(max_length=80),
        ),
        migrations.AlterField(
            model_name='section2',
            name='section',
            field=models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.section'),
        ),
        migrations.AlterField(
            model_name='section3',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='section3',
            name='section',
            field=models.ForeignKey(default=4, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.section'),
        ),
        migrations.AlterField(
            model_name='section3',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Section1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('emoji', models.CharField(max_length=2)),
                ('image', models.ImageField(upload_to='media/quantum_capabilities_img')),
                ('section', models.ForeignKey(default=2, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.section')),
            ],
            options={
                'verbose_name': 'Section2',
                'verbose_name_plural': 'Section2',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.CharField(max_length=5)),
                ('stat_label', models.FileField(max_length=30, upload_to='')),
                ('site_info', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.siteinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='Section4',
        ),
    ]
