# Generated by Django 5.2.7 on 2025-11-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_siteinfo_alter_section2_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='site_name',
            field=models.CharField(default='dd', max_length=30),
            preserve_default=False,
        ),
    ]
