# Generated by Django 5.2.7 on 2025-11-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_siteinfo_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='stat_label',
            field=models.CharField(max_length=30),
        ),
    ]
