# Generated by Django 5.2.7 on 2025-11-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_stat_stat_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='stat_label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stat',
            name='stat_value',
            field=models.CharField(max_length=10),
        ),
    ]
