# Generated by Django 5.2.7 on 2025-11-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_stat_stat_label_alter_stat_stat_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section1',
            options={'verbose_name_plural': 'Section1'},
        ),
        migrations.AlterModelOptions(
            name='section2',
            options={'verbose_name_plural': 'Section2'},
        ),
        migrations.AlterModelOptions(
            name='section3',
            options={'ordering': ['year'], 'verbose_name_plural': 'Section3'},
        ),
        migrations.AlterField(
            model_name='section1',
            name='image',
            field=models.ImageField(upload_to='media/section1_img'),
        ),
    ]
