# Generated by Django 5.2.7 on 2025-11-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_section1_options_alter_section2_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section1',
            name='emoji',
            field=models.CharField(max_length=4),
        ),
    ]
