# Generated by Django 5.2.7 on 2025-11-03 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_section1_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section1',
            name='section',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.section'),
        ),
        migrations.AlterField(
            model_name='section2',
            name='section',
            field=models.ForeignKey(default=2, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.section'),
        ),
        migrations.AlterField(
            model_name='section3',
            name='section',
            field=models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.section'),
        ),
        migrations.AlterField(
            model_name='section3',
            name='year',
            field=models.PositiveSmallIntegerField(max_length=4),
        ),
    ]
